### ISSUE TITLE
django-registration-redux notes

### ISSUE THREAD

**Issue by petersanchez** [funkybob/kitty-litter#1]
Quick couple of points:

1. `accounts/urls.py` needs `app_name = 'accounts'` in the file to be compatible with modern Django versions.
2. At the end of the article you reference `register/register.html` when it should be `register/register_form.html`
3. `UserRegistrationView` uses an incorrect url name for `success_url`, it should be `accounts:register-done`

Cool write up! Thanks again!

**Comment by funkybob** [comment]
Thanks for the feedback!

From my reading of it, (1) is needed if the same url patterns are used in the tree in multiple places.
I'm not convinced this is the case with this code, and would like to see the errors / warnings you received without.

I've added it now anyway.

(2) is now fixed.

(3) is now fixed.

**Comment by petersanchez** [comment]
Just to follow up the discussion on point 1.

The error was:

```django.core.exceptions.ImproperlyConfigured: Specifying a namespace in include() without providing an app_name is not supported. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.```

The urls.py entry was:

`path('accounts/', include('hyfm.accounts.urls', namespace='accounts')),`

According to the docs, you need to specify app name to specify namespace option when calling include. Or pass in a 2 tuples for the first argument.

https://docs.djangoproject.com/en/2.2/ref/urls/#include
