### ISSUE TITLE
consider ubuntu or implementation of that too

### ISSUE THREAD

**Issue by nh916** [funkybob/kitty-litter#3]
I think a ubuntu distro would be better because ubuntu is the most popular and because of its popularity less threatening
	I do understand that they are pretty similar
	Ubuntu would also appeal to more people

**Comment by funkybob** [comment]
Ubuntu is a debian derivative, and copies almost all the relevant parts for this tutorial.

Personally, given their history as just not understanding server mentality, I won't recommend its use anywhere, as popular as I understand it to be.

Windows is popular, too, and I don't recommend it for servers, either.

[Hey, you came to my blog for an opinionated approach, you're going to have to hear my opinions :) ]

**Comment by funkybob** [comment]
I had also considered calling this out specifically in the tute, but felt it unnecessary. I'll state my preferences, and imply the rest.
