### ISSUE TITLE
consider making the tutorial REALLY SIMPLE

### ISSUE THREAD

**Issue by nh916** [funkybob/kitty-litter#6]
i understand the # means sudo but if you could type out sudo it be all the better
	as a beginner i basically want to copy and paste until i am comfortable to do my own code
making the tutorial simple would be great

**Comment by funkybob** [comment]
Correction: # does _not_ mean sudo. It means "performed as root".

I will make explicit in the "Before we begin" section that we at no point use sudo.

I will make it clearer to log in as root, or to use "su" to switch from your normal user to root.
