### ISSUE TITLE
font problem and UI

### ISSUE THREAD

**Issue by nh916** [funkybob/kitty-litter#7]
font is small and everything is cramped together making it more threatening for a beginner to read through and ill just skip to another page that looks easy
	consider adding more icons, pictures, colors, and breaking each sections up so the user feels better as reader is going through it

	bigger heading would be appreciated

	a digital ocean logo and debian logo would be great to easily know what technology youll be working with fast!

**Comment by funkybob** [comment]
Design is not my strong suit :)

I did have some screen caps for the droplet setup stage, and will capture fresh ones when I go through it again for the refresh.

I'll tweak the style sheet to enlarge the gaps, and space out / break up the text more.

**Comment by funkybob** [comment]
I've boosted the base font size by 10% across the whole site.

IMHO this does look a lot easier to read.

**Comment by nh916** [comment]
the user should not have to look for it, it should be easily able to glance and have it be right there
